// <auto-generated />
using System;
using Certifications.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Certifications.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CertificationsDbContext))]
    [Migration("20260827143152_SeedCriminalPoliceDepartment")]
    partial class SeedCriminalPoliceDepartment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Certifications.Domain.Entities.Contract", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<DateOnly>("ContractDate")
                        .HasColumnType("date")
                        .HasColumnName("contract_date");

                    b.Property<string>("Department")
                        .HasColumnType("text")
                        .HasColumnName("department");

                    b.Property<string>("Division")
                        .HasColumnType("text")
                        .HasColumnName("division");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("position");

                    b.Property<int>("ProlongationAlertMonths")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("prolongation_alert_months");

                    b.Property<int>("ProlongationForYears")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("prolongation_for_years");

                    b.Property<int>("ProlongationWarningMonths")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(3)
                        .HasColumnName("prolongation_warning_months");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateOnly?>("ValidTo")
                        .HasColumnType("date")
                        .HasColumnName("valid_to");

                    b.HasKey("Id")
                        .HasName("pk_contracts");

                    b.HasIndex("Department")
                        .HasDatabaseName("ix_contracts_department");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("ix_contracts_employee_id");

                    b.HasIndex("ValidTo")
                        .HasDatabaseName("ix_contracts_valid_to");

                    b.HasIndex(new[] { "EmployeeId" }, "ux_contracts_employee_id_active_model")
                        .IsUnique()
                        .HasDatabaseName("ux_contracts_employee_id_active")
                        .HasFilter("active = TRUE");

                    b.ToTable("contracts", null, t =>
                        {
                            t.HasCheckConstraint("ck_contracts_renewal_settings", "prolongation_warning_months >= 0 AND prolongation_alert_months >= 0 AND prolongation_for_years > 0 AND prolongation_alert_months < prolongation_warning_months");
                        });

                    b.HasData(
                        new
                        {
                            Id = -1001L,
                            Active = true,
                            ContractDate = new DateOnly(2024, 1, 15),
                            Department = "Руководство департамента",
                            Division = "Департамент криминальной полиции",
                            EmployeeId = new Guid("c0000000-0000-0000-0000-000000000001"),
                            Position = "Начальник департамента",
                            ProlongationAlertMonths = 1,
                            ProlongationForYears = 1,
                            ProlongationWarningMonths = 3,
                            ValidTo = new DateOnly(2027, 12, 31)
                        },
                        new
                        {
                            Id = -1002L,
                            Active = true,
                            ContractDate = new DateOnly(2023, 11, 15),
                            Department = "Отдел уголовного розыска",
                            Division = "Департамент криминальной полиции",
                            EmployeeId = new Guid("c0000000-0000-0000-0000-000000000002"),
                            Position = "Начальник отдела",
                            ProlongationAlertMonths = 1,
                            ProlongationForYears = 1,
                            ProlongationWarningMonths = 3,
                            ValidTo = new DateOnly(2026, 11, 15)
                        },
                        new
                        {
                            Id = -1003L,
                            Active = true,
                            ContractDate = new DateOnly(2023, 9, 15),
                            Department = "Отдел уголовного розыска",
                            Division = "Департамент криминальной полиции",
                            EmployeeId = new Guid("c0000000-0000-0000-0000-000000000003"),
                            Position = "Старший оперуполномоченный",
                            ProlongationAlertMonths = 1,
                            ProlongationForYears = 1,
                            ProlongationWarningMonths = 3,
                            ValidTo = new DateOnly(2026, 9, 15)
                        },
                        new
                        {
                            Id = -1004L,
                            Active = true,
                            ContractDate = new DateOnly(2023, 8, 1),
                            Department = "Отдел уголовного розыска",
                            Division = "Департамент криминальной полиции",
                            EmployeeId = new Guid("c0000000-0000-0000-0000-000000000004"),
                            Position = "Оперуполномоченный",
                            ProlongationAlertMonths = 1,
                            ProlongationForYears = 1,
                            ProlongationWarningMonths = 3,
                            ValidTo = new DateOnly(2026, 8, 1)
                        },
                        new
                        {
                            Id = -1005L,
                            Active = true,
                            ContractDate = new DateOnly(2024, 7, 5),
                            Department = "Отдел криминального анализа",
                            Division = "Департамент криминальной полиции",
                            EmployeeId = new Guid("c0000000-0000-0000-0000-000000000005"),
                            Position = "Криминальный аналитик",
                            ProlongationAlertMonths = 1,
                            ProlongationForYears = 1,
                            ProlongationWarningMonths = 3,
                            ValidTo = new DateOnly(2027, 7, 5)
                        },
                        new
                        {
                            Id = -1006L,
                            Active = false,
                            ContractDate = new DateOnly(2022, 1, 10),
                            Department = "Отдел уголовного розыска",
                            Division = "Департамент криминальной полиции",
                            EmployeeId = new Guid("c0000000-0000-0000-0000-000000000006"),
                            Position = "Оперуполномоченный",
                            ProlongationAlertMonths = 1,
                            ProlongationForYears = 1,
                            ProlongationWarningMonths = 3,
                            ValidTo = new DateOnly(2025, 12, 31)
                        });
                });

            modelBuilder.Entity("Certifications.Domain.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("EncryptedPassword")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("encrypted_password");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("is_admin");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("MiddleName")
                        .HasColumnType("text")
                        .HasColumnName("middle_name");

                    b.Property<string>("NormalizedPersonalId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("normalized_personal_id");

                    b.Property<string>("PersonalId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("personal_id");

                    b.Property<string>("PreferredAdminMode")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("preferred_admin_mode");

                    b.HasKey("Id")
                        .HasName("pk_employees");

                    b.HasIndex("NormalizedPersonalId")
                        .IsUnique()
                        .HasDatabaseName("ux_employees_normalized_personal_id");

                    b.ToTable("employees", null, t =>
                        {
                            t.HasCheckConstraint("ck_employees_preferred_admin_mode_requires_admin", "preferred_admin_mode IS NULL OR is_admin = TRUE");

                            t.HasCheckConstraint("ck_employees_preferred_admin_mode_value", "preferred_admin_mode IS NULL OR preferred_admin_mode IN ('MyPage', 'Administration')");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000001"),
                            EncryptedPassword = "seed-data-password-not-provisioned",
                            FirstName = "Елена",
                            IsAdmin = true,
                            LastName = "Волкова",
                            MiddleName = "Сергеевна",
                            NormalizedPersonalId = "КП-0001",
                            PersonalId = "КП-0001",
                            PreferredAdminMode = "Administration"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000002"),
                            EncryptedPassword = "seed-data-password-not-provisioned",
                            FirstName = "Алексей",
                            IsAdmin = false,
                            LastName = "Морозов",
                            MiddleName = "Николаевич",
                            NormalizedPersonalId = "КП-0002",
                            PersonalId = "КП-0002"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000003"),
                            EncryptedPassword = "seed-data-password-not-provisioned",
                            FirstName = "Мария",
                            IsAdmin = false,
                            LastName = "Кузнецова",
                            MiddleName = "Андреевна",
                            NormalizedPersonalId = "КП-0003",
                            PersonalId = "КП-0003"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000004"),
                            EncryptedPassword = "seed-data-password-not-provisioned",
                            FirstName = "Дмитрий",
                            IsAdmin = false,
                            LastName = "Соколов",
                            MiddleName = "Олегович",
                            NormalizedPersonalId = "КП-0004",
                            PersonalId = "КП-0004"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000005"),
                            EncryptedPassword = "seed-data-password-not-provisioned",
                            FirstName = "Ирина",
                            IsAdmin = false,
                            LastName = "Лебедева",
                            MiddleName = "Павловна",
                            NormalizedPersonalId = "КП-0005",
                            PersonalId = "КП-0005"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000006"),
                            EncryptedPassword = "seed-data-password-not-provisioned",
                            FirstName = "Николай",
                            IsAdmin = false,
                            LastName = "Фёдоров",
                            MiddleName = "Евгеньевич",
                            NormalizedPersonalId = "КП-0006",
                            PersonalId = "КП-0006"
                        });
                });

            modelBuilder.Entity("Certifications.Domain.Entities.Prolongation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Assessor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("assessor");

                    b.Property<DateOnly>("CertificationDate")
                        .HasColumnType("date")
                        .HasColumnName("certification_date");

                    b.Property<long>("ContractId")
                        .HasColumnType("bigint")
                        .HasColumnName("contract_id");

                    b.Property<DateOnly?>("ProlongationReturned")
                        .HasColumnType("date")
                        .HasColumnName("prolongation_returned");

                    b.Property<DateOnly?>("ProlongationSend")
                        .HasColumnType("date")
                        .HasColumnName("prolongation_send");

                    b.Property<DateOnly?>("ProtocolDate")
                        .HasColumnType("date")
                        .HasColumnName("protocol_date");

                    b.HasKey("Id")
                        .HasName("pk_prolongations");

                    b.HasIndex("ContractId")
                        .IsUnique()
                        .HasDatabaseName("ux_prolongations_contract_id_in_progress")
                        .HasFilter("prolongation_returned IS NULL");

                    b.HasIndex("ContractId", "CertificationDate")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_prolongations_contract_id_certification_date");

                    b.ToTable("prolongations", null, t =>
                        {
                            t.HasCheckConstraint("ck_prolongations_date_sequence", "(protocol_date IS NULL OR protocol_date >= certification_date) AND (prolongation_send IS NULL OR (protocol_date IS NOT NULL AND prolongation_send >= protocol_date)) AND (prolongation_returned IS NULL OR (prolongation_send IS NOT NULL AND prolongation_returned >= prolongation_send))");
                        });

                    b.HasData(
                        new
                        {
                            Id = -2001L,
                            Assessor = "полковник полиции Виктор Петрович Громов",
                            CertificationDate = new DateOnly(2026, 8, 10),
                            ContractId = -1004L
                        },
                        new
                        {
                            Id = -2002L,
                            Assessor = "полковник полиции Виктор Петрович Громов",
                            CertificationDate = new DateOnly(2026, 7, 1),
                            ContractId = -1005L,
                            ProlongationReturned = new DateOnly(2026, 7, 20),
                            ProlongationSend = new DateOnly(2026, 7, 10),
                            ProtocolDate = new DateOnly(2026, 7, 5)
                        });
                });

            modelBuilder.Entity("Certifications.Domain.Entities.Contract", b =>
                {
                    b.HasOne("Certifications.Domain.Entities.Employee", null)
                        .WithMany("Contracts")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_contracts_employees_employee_id");
                });

            modelBuilder.Entity("Certifications.Domain.Entities.Prolongation", b =>
                {
                    b.HasOne("Certifications.Domain.Entities.Contract", null)
                        .WithMany("Prolongations")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_prolongations_contracts_contract_id");
                });

            modelBuilder.Entity("Certifications.Domain.Entities.Contract", b =>
                {
                    b.Navigation("Prolongations");
                });

            modelBuilder.Entity("Certifications.Domain.Entities.Employee", b =>
                {
                    b.Navigation("Contracts");
                });
#pragma warning restore 612, 618
        }
    }
}
